#!/usr/bin/env python
# -*- coding: utf-8 -*-

from flatfindr.facebook import Facebook
import random
import os
from time import sleep

while True:
    print(Facebook().update_db())
    sleep(random.uniform(25, 35) * 60)
