#!/usr/bin/env python
# -*- coding: utf-8 -*-

from flatfindr.facebook import Facebook
import random
import os
from time import sleep

while True:
    fb = Facebook()
    cookies_path = os.path.join(
        os.path.dirname(os.path.dirname(os.path.realpath(__file__))),
        "raw_data/cookies.pkl",
    )
    if not os.path.isfile(cookies_path):
        fb.log_in()
    else:
        fb.load_cookies()

    fb.get_items_links(
        min_price=1_200,
        max_price=1_750,
        min_bedrooms=2,
        lat=45.5254,
        lng=-73.5724,
        radius=2,
        scroll=10,
    )
    fb.get_items_details()
    fb.quit_driver()

    sleep(random.uniform(25, 35) * 60)
